### Importing relevant libraries

In [54]:
import pandas as pd
import numpy as np

In [55]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [56]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-07                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         0         1  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         0         1  2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2  
3         2     0                          4            7                3  
4         2     1                          2            7                3

### creating targets

In [57]:
absent_median = data_preprocessed['Absenteeism Time in Hours'].median()

In [58]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > absent_median, 1, 0)

In [59]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [60]:
data_preprocessed['Excessive Absenteeism'] = targets

In [61]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-07                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         0         1  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         0         1  2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  \
0         2     1                          4            7                1   
1         1     0                          0            7                1   
2         0     0                          2            7                2   
3         2     0                          4            7                3   
4         2     1                          2            7                3   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

### analysing targets

In [62]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [63]:
data_with_targets = data_preprocessed.drop(['Excessive Absenteeism'], axis=1)
data_with_targets = data_with_targets.drop(['Date'], axis=1)

In [64]:
data_with_targets is data_preprocessed

False

In [65]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   
3         1         0         0         0                     279   
4         0         0         0         1                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2  
3         2     0                          4            7                3  
4         2     1                          2            7                3

### selecting inputs for the regression

In [66]:
data_with_targets.shape

(700, 15)

In [67]:
data_with_targets.iloc[:,:14]

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0           0         0         0         1                     289   
1           0         0         0         0                     118   
2           0         0         0         1                     179   
3           1         0         0         0                     279   
4           0         0         0         1                     289   
..        ...       ...       ...       ...                     ...   
695         1         0         0         0                     179   
696         1         0         0         0                     225   
697         1         0         0         0                     330   
698         0         0         0         1                     235   
699         0         0         0         1                     291   

     Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
0                  36   33                  239.554               30   
1                  13   50                  239.554               31   
2                  51   38                  239.554               31   
3                   5   39                  239.554               24   
4                  36   33                  239.554               30   
..                ...  ...                      ...              ...   
695                22   40                  237.656               22   
696                26   28                  237.656               24   
697                16   28                  237.656               25   
698                16   32                  237.656               25   
699                31   40                  237.656               25   

     Education  Children  Pets  Absenteeism Time in Hours  Month Value  
0            0         2     1                          4            7  
1            0         1     0                          0            7  
2            0         0     0                          2            7  
3            0         2     0                          4            7  
4            0         2     1                          2            7  
..         ...       ...   ...                        ...          ...  
695          1         2     0                          8            5  
696          0         1     2                          3            5  
697          1         0     0                          8            5  
698          1         0     0                          2            5  
699          0         1     1                          2            5  

[700 rows x 14 columns]

In [68]:
data_with_targets.iloc[:,:-3]

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0           0         0         0         1                     289   
1           0         0         0         0                     118   
2           0         0         0         1                     179   
3           1         0         0         0                     279   
4           0         0         0         1                     289   
..        ...       ...       ...       ...                     ...   
695         1         0         0         0                     179   
696         1         0         0         0                     225   
697         1         0         0         0                     330   
698         0         0         0         1                     235   
699         0         0         0         1                     291   

     Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
0                  36   33                  239.554               30   
1                  13   50                  239.554               31   
2                  51   38                  239.554               31   
3                   5   39                  239.554               24   
4                  36   33                  239.554               30   
..                ...  ...                      ...              ...   
695                22   40                  237.656               22   
696                26   28                  237.656               24   
697                16   28                  237.656               25   
698                16   32                  237.656               25   
699                31   40                  237.656               25   

     Education  Children  Pets  
0            0         2     1  
1            0         1     0  
2            0         0     0  
3            0         2     0  
4            0         2     1  
..         ...       ...   ...  
695          1         2     0  
696          0         1     2  
697          1         0     0  
698          1         0     0  
699          0         1     1  

[700 rows x 12 columns]

In [69]:
#unscaled_inputs = data_with_targets.iloc[:,:-3]
unscaled_inputs = data_with_targets.drop(['Absenteeism Time in Hours'], axis=1)

In [70]:
unscaled_inputs.head()

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   
3         1         0         0         0                     279   
4         0         0         0         1                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Month Value  Day of the Week  
0         2     1            7                1  
1         1     0            7                1  
2         0     0            7                2  
3         2     0            7                3  
4         2     1            7                3

### standardizing the data

In [71]:
#from sklearn.preprocessing import StandardScaler

#absenteeism_scaler = StandardScaler()

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin):   

    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do

    def __init__(self,columns):   
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler()
        # with some columns 'twist'
        self.columns = columns     


    # the fit method, which, again based on StandardScale
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self

    # the transform method which does the actual scaling
    def transform(self, X, y=None):
        # record the initial order of the columns
        init_col_order = X.columns  
        print(self.columns)
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
         # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [72]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value', 'Day of the Week'], dtype=object)

In [73]:
columns_to_scale = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value', 'Day of the Week']

In [74]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [75]:
absenteeism_scaler.fit(unscaled_inputs)

C:\Users\luiss\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:757: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
C:\Users\luiss\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:595: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\luiss\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:604: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\luiss\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\fromnumeric.py:3785: FutureWarning: 

CustomScaler(columns=['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
                      'Transportation Expense', 'Distance to Work', 'Age',
                      'Daily Work Load Average', 'Body Mass Index', 'Education',
                      'Children', 'Pets', 'Month Value', 'Day of the Week'])

In [76]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Transportation Expense', 'Distance to Work', 'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children', 'Pets', 'Month Value', 'Day of the Week']


C:\Users\luiss\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:757: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
C:\Users\luiss\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:595: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\luiss\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:604: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):


#### spliting the data into train & test and shuffle

In [77]:
from sklearn.model_selection import train_test_split

In [78]:
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
 191  1.732051 -0.092981 -0.314485 -1.217485               -0.654143   
 395 -0.577350 -0.092981 -0.314485  0.821365                0.190942   
 557 -0.577350 -0.092981 -0.314485  0.821365                0.040034   
 312 -0.577350 -0.092981 -0.314485 -1.217485                1.036026   
 54  -0.577350 -0.092981 -0.314485 -1.217485                1.005844   
 ..        ...       ...       ...       ...                     ...   
 536  1.732051 -0.092981 -0.314485 -1.217485               -1.574681   
 31  -0.577350 -0.092981  3.179797 -1.217485                0.190942   
 98  -0.577350 -0.092981 -0.314485  0.821365                0.387122   
 657 -0.577350 -0.092981  3.179797 -1.217485                0.387122   
 522 -0.577350 -0.092981 -0.314485  0.821365                1.036026   
 
      Distance to Work       Age  Daily Work Load Average  Body Mass Index  \
 191          1.426749  0.248310                 1.36648

In [79]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=0.8, random_state = 20)

In [80]:
print(x_train.shape, y_train.shape)

(560, 14) (560,)


In [81]:
print(x_test.shape, y_test.shape)

(140, 14) (140,)


#### Logistic regression with sklearn

In [82]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [83]:
reg = LogisticRegression()

In [84]:
reg.fit(x_train,y_train)

C:\Users\luiss\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:757: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
C:\Users\luiss\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:595: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\luiss\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:604: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):


LogisticRegression()

In [85]:
reg.score(x_train, y_train)

C:\Users\luiss\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:757: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
C:\Users\luiss\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:595: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\luiss\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:604: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):


0.7839285714285714

#### manually checking the accuracy

In [86]:
model_outputs = reg.predict(x_train)

C:\Users\luiss\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:757: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
C:\Users\luiss\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:595: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\luiss\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:604: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):


In [87]:
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [88]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [89]:
np.sum((model_outputs == y_train))

439

In [90]:
model_outputs.shape[0]

560

In [91]:
np.sum((model_outputs==y_train)) / model_outputs.shape[0]

0.7839285714285714

### finding the intercept and coefficients

In [92]:
reg.intercept_

array([-0.22206736])

In [93]:
reg.coef_

array([[ 2.07601767,  0.33504757,  1.56162303,  1.32927434,  0.70639316,
        -0.03986811, -0.20089491, -0.00456366,  0.31933564, -0.135508  ,
         0.38172443, -0.3332426 ,  0.18793677, -0.07062253]])

In [94]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value', 'Day of the Week'], dtype=object)

In [95]:
feature_name = unscaled_inputs.columns.values

In [96]:
summary_table = pd.DataFrame(columns=['Feature name'], data=feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                  Reason_1     2.076018
1                  Reason_2     0.335048
2                  Reason_3     1.561623
3                  Reason_4     1.329274
4    Transportation Expense     0.706393
5          Distance to Work    -0.039868
6                       Age    -0.200895
7   Daily Work Load Average    -0.004564
8           Body Mass Index     0.319336
9                 Education    -0.135508
10                 Children     0.381724
11                     Pets    -0.333243
12              Month Value     0.187937
13          Day of the Week    -0.070623

In [97]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                 Intercept    -0.222067
1                  Reason_1     2.076018
2                  Reason_2     0.335048
3                  Reason_3     1.561623
4                  Reason_4     1.329274
5    Transportation Expense     0.706393
6          Distance to Work    -0.039868
7                       Age    -0.200895
8   Daily Work Load Average    -0.004564
9           Body Mass Index     0.319336
10                Education    -0.135508
11                 Children     0.381724
12                     Pets    -0.333243
13              Month Value     0.187937
14          Day of the Week    -0.070623

#### interpreting the coefficients

In [98]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)
summary_table

Feature name  Coefficient  Odds_ratio
0                 Intercept    -0.222067    0.800861
1                  Reason_1     2.076018    7.972656
2                  Reason_2     0.335048    1.398007
3                  Reason_3     1.561623    4.766551
4                  Reason_4     1.329274    3.778301
5    Transportation Expense     0.706393    2.026668
6          Distance to Work    -0.039868    0.960916
7                       Age    -0.200895    0.817998
8   Daily Work Load Average    -0.004564    0.995447
9           Body Mass Index     0.319336    1.376213
10                Education    -0.135508    0.873272
11                 Children     0.381724    1.464808
12                     Pets    -0.333243    0.716596
13              Month Value     0.187937    1.206757
14          Day of the Week    -0.070623    0.931814

In [99]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
1                  Reason_1     2.076018    7.972656
3                  Reason_3     1.561623    4.766551
4                  Reason_4     1.329274    3.778301
5    Transportation Expense     0.706393    2.026668
11                 Children     0.381724    1.464808
2                  Reason_2     0.335048    1.398007
9           Body Mass Index     0.319336    1.376213
13              Month Value     0.187937    1.206757
8   Daily Work Load Average    -0.004564    0.995447
6          Distance to Work    -0.039868    0.960916
14          Day of the Week    -0.070623    0.931814
10                Education    -0.135508    0.873272
7                       Age    -0.200895    0.817998
0                 Intercept    -0.222067    0.800861
12                     Pets    -0.333243    0.716596

### testing model

In [100]:
reg.score(x_test, y_test)

C:\Users\luiss\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:757: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
C:\Users\luiss\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:595: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\luiss\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:604: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):


0.7357142857142858

In [101]:
predicted_poba = reg.predict_proba(x_test)

C:\Users\luiss\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:757: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
C:\Users\luiss\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:595: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\luiss\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:604: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):


In [102]:
predicted_poba

array([[0.73864865, 0.26135135],
       [0.58845661, 0.41154339],
       [0.36763564, 0.63236436],
       [0.81198089, 0.18801911],
       [0.0613996 , 0.9386004 ],
       [0.30742403, 0.69257597],
       [0.29538175, 0.70461825],
       [0.08106026, 0.91893974],
       [0.80435611, 0.19564389],
       [0.76038732, 0.23961268],
       [0.46271934, 0.53728066],
       [0.15484755, 0.84515245],
       [0.04619732, 0.95380268],
       [0.72991038, 0.27008962],
       [0.23140393, 0.76859607],
       [0.55130442, 0.44869558],
       [0.5292476 , 0.4707524 ],
       [0.55522744, 0.44477256],
       [0.38197963, 0.61802037],
       [0.02527634, 0.97472366],
       [0.69617984, 0.30382016],
       [0.80458387, 0.19541613],
       [0.37734902, 0.62265098],
       [0.40003074, 0.59996926],
       [0.18229161, 0.81770839],
       [0.76011784, 0.23988216],
       [0.47050402, 0.52949598],
       [0.88997625, 0.11002375],
       [0.13577639, 0.86422361],
       [0.7969686 , 0.2030314 ],
       [0.

In [103]:
predicted_poba[:,1]

array([0.26135135, 0.41154339, 0.63236436, 0.18801911, 0.9386004 ,
       0.69257597, 0.70461825, 0.91893974, 0.19564389, 0.23961268,
       0.53728066, 0.84515245, 0.95380268, 0.27008962, 0.76859607,
       0.44869558, 0.4707524 , 0.44477256, 0.61802037, 0.97472366,
       0.30382016, 0.19541613, 0.62265098, 0.59996926, 0.81770839,
       0.23988216, 0.52949598, 0.11002375, 0.86422361, 0.2030314 ,
       0.38454827, 0.70459151, 0.70138178, 0.56363893, 0.19541613,
       0.54256241, 0.20504956, 0.82072323, 0.44466019, 0.61108219,
       0.20908782, 0.40281153, 0.21373621, 0.09844091, 0.84224496,
       0.66612989, 0.71672931, 0.26982044, 0.20155736, 0.17070043,
       0.5733945 , 0.08298962, 0.67931742, 0.28630329, 0.87253409,
       0.48546569, 0.9325331 , 0.2462249 , 0.08169672, 0.08239341,
       0.72795552, 0.6695154 , 0.31201864, 0.86026294, 0.1838827 ,
       0.2596655 , 0.0131662 , 0.22029913, 0.8123649 , 0.31453865,
       0.20433741, 0.07128014, 0.93325923, 0.46319471, 0.65517

### save model

In [104]:
import pickle

In [105]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [106]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)